### ISSUE TITLE
Try to add system user login details 👨‍💻👩‍💻

### ISSUE THREAD

**Issue by Ash515** [Ash515/AshTech-AI_Personal_Voice_Assistant#10]
Try to add user login details in our system. Our AshTech should give the clear information about **user login details and login counts**.

**Comment by Vashuev** [comment]
@Ash515 hey, which system are you talking about? is it our device (laptop, computer) or our AskTech system login

**Comment by Ash515** [comment]
device details

**Comment by realhunter7869** [comment]
Hey @Ash515 can you assign this to me

**Comment by Ash515** [comment]
sure
