### ISSUE TITLE
print all the module installed in python

### ISSUE THREAD

**Issue by pranabprohit** [Ash515/AshTech-AI_Personal_Voice_Assistant#107]
Ask assistant to print all the installed module in python in alphabetical order.

**Comment by pranabprohit** [comment]
@Ash515, I would like to work on this issue as a part of CWOC. Can you assign this issue to me.

**Comment by Ash515** [comment]
sure

**Comment by pranabprohit** [comment]
@Ash515 there are no lables on this issue. Please add the required lables. :)

**Comment by pranabprohit** [comment]
@Ash515, Please add the required labels to this issue.
