### ISSUE TITLE
associate link of the crosswoc website to its banner

### ISSUE THREAD

**Issue by yashlikescode** [Ash515/AshTech-AI_Personal_Voice_Assistant#109]
I will associate link of the crosswoc website to its banner such that, if someone clicks the banner on readme file, it will redirect them to the website of crosswoc.

**Comment by Ash515** [comment]
Nice All the very best

**Comment by yashlikescode** [comment]
Why aren't you merging it, is there any problem?

**Comment by Ash515** [comment]
Are you gave PR ?

**Comment by Ash515** [comment]
Hi  @kmryashasvi  did you gave PR for this issue ?

**Comment by yashlikescode** [comment]
Yes, of course

**Comment by yashlikescode** [comment]
It is pr no. #112

**Comment by anjali1102** [comment]
is this issue pending? I think @kmryashasvi  has done some work on this?

**Comment by yashlikescode** [comment]
> is this issue pending? I think @kmryashasvi has done some work on this?

Its not pending,  but PR related to it is yet to be merged

**Comment by yashlikescode** [comment]
@Ash515 Why you closed the issue and why aren't you merging the PR?

**Comment by Ash515** [comment]
Have you submitted the PR or not Mr @kmryashasvi

**Comment by yashlikescode** [comment]
> Have you submitted the PR or not Mr @kmryashasvi

Yes, it is pr #112 and it was pulled 13 days ago. Why don't you understand?
Are you new on github?
you have asked this question twice, even when I had answered it before
@Ash515

**Comment by Ash515** [comment]
Sorry Mr @kmryashasvi for misunderstanding and one more thing please mind your words when speaking with someone.
Thank you !

**Comment by yashlikescode** [comment]
> Sorry Mr @kmryashasvi for misunderstanding and one more thing please mind your words when speaking with someone.
> Thank you !

What my words?

**Comment by Ash515** [comment]
Nothing thanks
