### ISSUE TITLE
wifi names and their passwords in txt file.

### ISSUE THREAD

**Issue by pranabprohit** [Ash515/AshTech-AI_Personal_Voice_Assistant#111]
It would be great if our ashtech could fetch all the connected wifi names and their passwords and store them in a txt file.

**Comment by pranabprohit** [comment]
Hi @Ash515, I would like to work on this issue as a part of CWOC. Can you please assign this issue to me.

**Comment by Ash515** [comment]
I'm sorry  it is not a good activity just try to do another issue

**Comment by pranabprohit** [comment]
> I'm sorry it is not a good activity just try to do another issue

@Ash515, I think you are getting it wrong it will fetch the password of only those wifi's to which user has already connected before. (Like I have connected to 2 wifi through my device so it will only fetch those wifi password as they are store in my system)

**Comment by Ash515** [comment]
Okay @pranabprohit  you do, and sorry for that mistake 😊

**Comment by pranabprohit** [comment]
@Ash515, don't you think that it should come under hard issue.
