### ISSUE TITLE
Add feature to tell motivational quote 

### ISSUE THREAD

**Issue by Akash20x** [Ash515/AshTech-AI_Personal_Voice_Assistant#114]
**Is your feature request related to a problem? Please describe.**
----
Assistant gives random motivational quote 

**Describe the solution you'd like**
----
When a user motivational quote, it gives users 4-5 categories and user have to select, then it provides random motivational quote related to that category 
.
**Additional context**
----
- Add any other context or screenshots about the feature request here.

**Comment by Akash20x** [comment]
Please consider this and assign me this issue as a part of Cross Woc

**Comment by Akash20x** [comment]
Please also assign me this issue

**Comment by Akash20x** [comment]
Any update on my above comment

**Comment by Ash515** [comment]
You can do this

**Comment by Ash515** [comment]
You can do this

**Comment by Akash20x** [comment]
OK

**Comment by Akash20x** [comment]
Sorry, I forgot to solve this I will reopen it if I get time to solve it

**Comment by Ash515** [comment]
Ok

**Comment by anjali1102** [comment]
Hey @Ash515 Please consider adding "hard" Label as I have added randomly generated GUI based if you feel so

**Comment by Ash515** [comment]
sure
