### ISSUE TITLE
Control system volume

### ISSUE THREAD

**Issue by pranabprohit** [Ash515/AshTech-AI_Personal_Voice_Assistant#119]
Ask assistant to control volume of our system like volume-up, volume-down and mute.

**Comment by pranabprohit** [comment]
hello @Ash515, I would like to work on this issue as a part of CWOC.

**Comment by pranabprohit** [comment]
hello @Ash515, I would like to work on this issue as a part of CWOC.

**Comment by Ash515** [comment]
Sure All the best
