### ISSUE TITLE
Detecting walking feet counts 🦿🦾

### ISSUE THREAD

**Issue by Ash515** [Ash515/AshTech-AI_Personal_Voice_Assistant#12]
It would be nice if our AshTech would detect the exact walking feet count per day.

**Comment by AmalChandru** [comment]
Can I work on this?

**Comment by Ash515** [comment]
Sure @AmalChandru All the very best

**Comment by Amit366** [comment]
@Ash515  can I work on this issue??

**Comment by Ash515** [comment]
sure

**Comment by Amit366** [comment]
@Ash515 I am not finding the dataset. Could you help me with dataset?

**Comment by Ash515** [comment]
yeah

**Comment by Amit366** [comment]
@Ash515 sir what about the dataset??

**Comment by Ash515** [comment]
Exactly what dataset do you want?

**Comment by Amit366** [comment]
I want a dataset of different activities like standing, walking and running

**Comment by Amit366** [comment]
@Ash515 sir I found one dataset where there are step count for different days. I am thinking to represent it in a form of statistics that is bar chart, central tendency .

**Comment by Amit366** [comment]
If you agree I will work on it.

**Comment by Ash515** [comment]
yeah try that All the very best

**Comment by Amit366** [comment]
@Ash515 sir I have sent the PR. Please check it.

**Comment by Amit366** [comment]
@Ash515 please add the tags to the merged PR

**Comment by Amit366** [comment]
@Ash515 Can you add the CWOC tag to the merged PR

> @Ash515 sir I have sent the PR. Please check it.

@Ash515 could you please the CWOC tag to this PR??

**Comment by Ash515** [comment]
I think you this PR is belonged to  DWOC ??

**Comment by Amit366** [comment]
Yes I belong to both DWOC and Cwoc

**Comment by Amit366** [comment]
I registered for CWOC and I saw this project also so I am asking to add. @Ash515

**Comment by Ash515** [comment]
Sorry this issue is not a part of CWOC. Try to solve the issue assigned with the tag of Cwoc
