### ISSUE TITLE
Ask assistant to hide/unhide file or folder

### ISSUE THREAD

**Issue by pranabprohit** [Ash515/AshTech-AI_Personal_Voice_Assistant#125]
It would be great if our assistant could hide the file and folder. We can do that by going to properties and hide them but anyone can unhide them. So to hide it properly ask assistant to hide the folder using cmd.

**Comment by pranabprohit** [comment]
@Ash515, I would like to work on this issue as a part of CWOC.

**Comment by Ash515** [comment]
sure
