### ISSUE TITLE
Opening OS Programs like word etc using voice commands

### ISSUE THREAD

**Issue by manvi0308** [Ash515/AshTech-AI_Personal_Voice_Assistant#13]

**Comment by Cruel-Crab** [comment]
I am interested in this issue;
Kindly assign it to me.

**Comment by Ash515** [comment]
Sure @Cruel-Crab All the very best

**Comment by Amitdutta7** [comment]
Can I work on this too. I have a basic understanding of the **OS module**.

**Comment by realhunter7869** [comment]
I am interested

**Comment by Ash515** [comment]
All the very best !

**Comment by realhunter7869** [comment]
Dear @Ash515  can you please merge this into main branch

**Comment by Ash515** [comment]
@realhunter7869 I cant understand your query please tell again
