### ISSUE TITLE
open geeksforgeeks, github

### ISSUE THREAD

**Issue by pranabprohit** [Ash515/AshTech-AI_Personal_Voice_Assistant#131]
it would be great if our ashtech could open geeksforgeeks, github.

**Comment by pranabprohit** [comment]
Hii @Ash515 , I would like to work on this issue as a part of CWOC.

**Comment by Ash515** [comment]
Already it will open gmail you can try with other two sites

**Comment by pranabprohit** [comment]
> Already it will open gmail you can try with other two sites

Okay
