### ISSUE TITLE
Web scraping to get some news headlines

### ISSUE THREAD

**Issue by manvi0308** [Ash515/AshTech-AI_Personal_Voice_Assistant#14]
We can use **WEB SCRAPING** to fetch the latest headlines from a newspaper, that will give notifications after every hour of the top headlines

- [ ] Web scraping to get news headlines
- [ ] Setting it as notification remainder after every hour or so

**Comment by AlexVines** [comment]
Hey! I was doing web scrapping using bs4 on UpWork, so maybe I can help?

**Comment by Ash515** [comment]
Great!

**Comment by samruddhi-10** [comment]
Hi,
I am new to webscraping want to try some hands-on, could you please assign it to me too?

**Comment by Ash515** [comment]
Sure All the very best @samruddhi-10  and @AlexVines you can also do I also assign you also.

**Comment by sahebsunny** [comment]
Sir, Let me work on it.
I would be grateful if you can assign this issue to me.

**Comment by sahebsunny** [comment]
sir, I am waiting for your permission so that I can Work on it

**Comment by Ash515** [comment]
Sure @sahebsunny  sorry for late reply you can do All the very best

**Comment by keshav340** [comment]
Can I do this
