### ISSUE TITLE
Asking the AI Voice Assistant to tell some jokes

### ISSUE THREAD

**Issue by 0xamitdutta** [Ash515/AshTech-AI_Personal_Voice_Assistant#17]
I think it'll be cool if you can ask the AI Voice Assistant to tell some jokes to cheer up the mood.
I think I can work on this. Kindly assign it to me.

**Comment by Amitdutta7** [comment]
Hey! Can I work on this. Kindly assign it to me.

**Comment by Ash515** [comment]
Yeah, nice All the very best !

**Comment by Vidura-Wijekoon** [comment]
I would like to work on this issue as a part of DWOC2020. I am a beginner level student and I want to learn more about the AI with emotional intelligence by studying this issue.

**Comment by Ash515** [comment]
Sure @Vidura-Wijekoon All the very best

**Comment by sahebsunny** [comment]
Sir, it's an interesting idea.
if the issue is open please let me work on it

**Comment by Akashdeep-47** [comment]
I would like to work on this issue. If open please let me know.

**Comment by Ash515** [comment]
Yes guys @sahebsunny and @Akashdeep-47 you can start work on this issue All the very best
