### ISSUE TITLE
There is only less shopping functions are here 💣🛒

### ISSUE THREAD

**Issue by Ash515** [Ash515/AshTech-AI_Personal_Voice_Assistant#3]
Hi everyone ! There is only less **shopping website function** are here so try to add more shopping website functions to boot up our AshTech 😍

**Comment by SubhradeepSS** [comment]
@Ash515 can i work on this issue for DWOC and add some other websites like flipkart,myntra etc.?

**Comment by Ash515** [comment]
sure @SubhradeepSS All the very best
