### ISSUE TITLE
Code of Conduct File

### ISSUE THREAD

**Issue by akrish4** [Ash515/AshTech-AI_Personal_Voice_Assistant#33]
Hi @Ash515 
I noticed there is no code of conduct file in this repository , I would like to work on this issue , kindly assign me

**Comment by Ash515** [comment]
Sure @akrish4 you can All the very best

**Comment by akrish4** [comment]
Hi @Ash515 
I have worked on it , Kindly checck anad merge it #34

**Comment by akrish4** [comment]
Hi @Ash515 
Kindly add `DWOC`and `Level 1` labels also in the PR otherwise it won't be counted.

**Comment by Ash515** [comment]
Done @akrish4
