### ISSUE TITLE
issue and pull request templates

### ISSUE THREAD

**Issue by akrish4** [Ash515/AshTech-AI_Personal_Voice_Assistant#35]
Hi @Ash515 

### You might have seen these templates before while opening a issue or pull request

![issue1](https://user-images.githubusercontent.com/61831021/103371378-4fba8980-4af5-11eb-98d6-dc40758f5c0d.PNG)
![issue2](https://user-images.githubusercontent.com/61831021/103371384-521ce380-4af5-11eb-992a-c306aa546cd3.PNG)
![github1](https://user-images.githubusercontent.com/61831021/103371388-534e1080-4af5-11eb-82e0-c83090182285.PNG)

These are the templates that help maintainers understand about the issue in detail
When ever a perosn opens a issue he/she needs to select whether it is a bug issue or feature issue , similarly when open a pull reuqest theye need to give a detail abt the PR and need to checklist few things which makes easy for a maintainer to understand and check accordingly.

Let me know if you want to add this feature to your repository ?

Kindly assign me

If you want to check this feature you go through [this](https://github.com/akrish4/Learn-By-Write/issues/new/choose)

**Comment by akrish4** [comment]
Kindly note this is feature update for your  github repository

**Comment by Ash515** [comment]
Yeah sure @akrish4 do it All the very best

**Comment by akrish4** [comment]
Hi @Ash515 
I haave worked on this issue and opened a pr on it 
Kindly do merge it and laso pls add the same labels added on this issue to pr also 
#44
