### ISSUE TITLE
Adding emotion recognition 

### ISSUE THREAD

**Issue by Bhagyashri2000** [Ash515/AshTech-AI_Personal_Voice_Assistant#37]
It would be great if the assistant would recognize user's emotion (good mood or upset) after first statement. We can use deep learning model for that.

**Comment by Ash515** [comment]
Sure @Bhagyashri2000 All the very best

**Comment by keshav340** [comment]
can I do this

**Comment by keshav340** [comment]
Can I do this

**Comment by Amit366** [comment]
@Ash515 can I work on this??

**Comment by Amit366** [comment]
@Ash515 sir can I work on this issue??

**Comment by Ash515** [comment]
yes you can
