### ISSUE TITLE
Messaging and writing notes.

### ISSUE THREAD

**Issue by bhavya092** [Ash515/AshTech-AI_Personal_Voice_Assistant#38]
It would be great if the AI could send whatsapp messages to any desired person as well as write notes with a voice command.

**Comment by Ash515** [comment]
Yes you can

**Comment by realhunter7869** [comment]
I would like to take this issue too

**Comment by Ash515** [comment]
Ok @realhunter7869 All the very best

**Comment by realhunter7869** [comment]
Hey @Ash515 please assign this to me

**Comment by Ash515** [comment]
Sure All the very best
