### ISSUE TITLE
There is no any job recommandation functions

### ISSUE THREAD

**Issue by Ash515** [Ash515/AshTech-AI_Personal_Voice_Assistant#4]
Hi young techs ! It would be very nice if AshTech had  some  **job recommendation websites** , so try to add some Job recommendation website functions like Glassdoor, LinkedIn, Indeed etc.😎

**Comment by sahebsunny** [comment]
Sir, Let me work on it.
I would be grateful if you can assign this issue to me.

**Comment by realhunter7869** [comment]
Sir can you assign this issue plz...

**Comment by Ash515** [comment]
Sure @realhunter7869 All the very best !

**Comment by Ash515** [comment]
Hey guys I am closing this issue now if you want to add any new features kindly comment then I will reopen this.
