### ISSUE TITLE
There is no any ticket booking functionalities 😕

### ISSUE THREAD

**Issue by Ash515** [Ash515/AshTech-AI_Personal_Voice_Assistant#6]
Hello Amigos ! We all know how it is very hard to get a ticket from the theatre 😕 so it is very helpful to train our AshTech with some **Film ticket booking websites** using functions to get the ticket booking websites easily to book our tickets. Not only for theatres you can also create functions for bus, train, aeroplane booking if you can. 🤩   ✈🚕🚊

**Comment by realhunter7869** [comment]
Hey @Ash515 can you assign this issue to me

**Comment by Ash515** [comment]
yeah sure All the very best

**Comment by Abithaa123** [comment]
Hey Ash515 can I do this ?

**Comment by Ash515** [comment]
Yes @Abithaa123 you can All the very best
