### ISSUE TITLE
Adding a code to say device hardware and architecture of currently using device

### ISSUE THREAD

**Issue by realhunter7869** [Ash515/AshTech-AI_Personal_Voice_Assistant#62]
**Is your feature request related to a problem? Please describe.**
Many a times we get questions about what our device hardware is. Let our AshTech answer that...
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
Assign me this issue and I can get this done
- A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
My solution works.
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Nope
- Add any other context or screenshots about the feature request here.

**Comment by realhunter7869** [comment]
Hey @Ash515 please assign DWOC label and level and assign this issue to me

**Comment by realhunter7869** [comment]
Hey @Ash515 please assign labels

**Comment by Ash515** [comment]
Yeah done All the very best
