### ISSUE TITLE
If it would be nice to have COVID19 Tracker 🦠 📊

### ISSUE THREAD

**Issue by Ash515** [Ash515/AshTech-AI_Personal_Voice_Assistant#7]
Hello peers ! I hope all are safe and good ❤. In this COVID19 periods peoples should know  the status of **infections, deaths and cure details** so it would be great to have such functionalities to our AshTech.

**Comment by sahebsunny** [comment]
Sir, I previously worked on a similar project,
I love to work on it.
I would be grateful if you can assign this issue to me for DSWOC.
Thank you.

**Comment by Ash515** [comment]
All the very best.

**Comment by sahebsunny** [comment]
Thank you sir

**Comment by Jithendra-k** [comment]
May i have a chance to work on this issue sir.
If yes, I was very happy to work on this

**Comment by Ash515** [comment]
Sure @Jithendra-k All the very best !!

**Comment by Ash515** [comment]
Guys I have closed this issue if you want to add more features in this particular issue kindly comment and I will reopen this issue Thank you !
