### ISSUE TITLE
It is good have a sports score predicting feature 

### ISSUE THREAD

**Issue by Ash515** [Ash515/AshTech-AI_Personal_Voice_Assistant#74]
When someone asks the sports score it should share with him/her

**Comment by ArkajyotiChakraborty** [comment]
Good Evening Sir, I want to contribute in this project and bring the best out of it.

**Comment by Ash515** [comment]
Are you belong to  CWOC21 ?

**Comment by ArkajyotiChakraborty** [comment]
yes sir, but i have very basic knowledge of python.

**Comment by Ash515** [comment]
Ok you can do it All the very best

**Comment by ArkajyotiChakraborty** [comment]
Sir, can u provide any source where i can find content related this as im new in python and also what is the deadline as my test are scheduled so i will sort everything accordingly.
Thanks a lot for collaboration.

**Comment by anjali1102** [comment]
Hey, @Ash515  I'll complete this task. Kindly assign a CWOC21 label if you don't mind.

**Comment by Ash515** [comment]
Done !
