### ISSUE TITLE
Date of birth predicts system 

### ISSUE THREAD

**Issue by Ash515** [Ash515/AshTech-AI_Personal_Voice_Assistant#75]
When he or she asks some friends or relatives birthday date to our Ashtech it should share.

**Comment by anjali1102** [comment]
taking up this issue ! Assign me

**Comment by Ash515** [comment]
Can I know which program do you belong to ?

**Comment by anjali1102** [comment]
crossWoc/CWOC21

**Comment by anjali1102** [comment]
Hey , prediction of birthdate of user or voice assistant? Please elaborate it more

**Comment by Ash515** [comment]
Users or them relatives or friends birthdates
