### ISSUE TITLE
It is nice to surf some topics in the browser 

### ISSUE THREAD

**Issue by Ash515** [Ash515/AshTech-AI_Personal_Voice_Assistant#77]
When a user asks to find some definitions or anything on the internet it should find and share with us.

**Comment by Akash20x** [comment]
Can you please assign me this issue as a part of Cross Woc. I would be very happy to do it

**Comment by Ash515** [comment]
yes you can all the very best !

**Comment by Akash20x** [comment]
I added the pull request for this issue, you can verify it.
