### ISSUE TITLE
Try to add some online courses websites 👨‍💻

### ISSUE THREAD

**Issue by Ash515** [Ash515/AshTech-AI_Personal_Voice_Assistant#8]
Try to add some online courses websites functions.

**Comment by sahebsunny** [comment]
Sir, I love to work on it.
I would be grateful if you can assign this issue to me for DSWOC.
Thank you.

**Comment by Ash515** [comment]
All the very best

**Comment by sahebsunny** [comment]
Thank you sir

**Comment by Jithendra-k** [comment]
Do i have a chance to work on this issue.
and also I want to contribute more to this.
I yes, I was happy to work on this

**Comment by Ash515** [comment]
Sure @Jithendra-k All the very best !

**Comment by Nitesh-thapliyal** [comment]
Can I work on this?

**Comment by Jithendra-k** [comment]
Its open to all I think @Nitesh-thapliyal .You can proceed.I am also working on this.good luck

**Comment by realhunter7869** [comment]
Can I get this issue.... I need to add on some features...

**Comment by Ash515** [comment]
Sure @realhunter7869 All the very best

**Comment by Ash515** [comment]
Hey u guys I am closing this issue now if you have any new idea kindly comment I will reopen this issue.
Thank you !
