### ISSUE TITLE
Add a GitHub action to auto-assign Mentors for every PR

### ISSUE THREAD

**Issue by muthuannamalai12** [Ash515/AshTech-AI_Personal_Voice_Assistant#92]
I would like to add a GitHub action to auto-assign mentors for every PR. It sometimes becomes hectic for the mentors to take a look at all the Projects for the PRs made by the Contributors. This action would give a nice notification about reviewing the pr and make things pretty easy for the mentor. It would automatically ask for reviews by the mentors on every pr created.

Demo :
![auto assign](https://user-images.githubusercontent.com/64524822/108363403-e44e8780-721a-11eb-96ff-ac4d8338e9b4.png)

**Comment by muthuannamalai12** [comment]
I would to work on it as a part of DWOC. Kindly assign it to me

**Comment by Ash515** [comment]
Sure
