### ISSUE TITLE
Open on - screen keyboard ⌨️

### ISSUE THREAD

**Issue by pranabprohit** [Ash515/AshTech-AI_Personal_Voice_Assistant#96]
It would be great if our assistant could open on-screen keyboard as many time we face difficulty with physical keyboard.

**Comment by pranabprohit** [comment]
I would like to work on this issue as part of DWOC . Can you please assign this issue to me ?

**Comment by pranabprohit** [comment]
> I would like to work on this issue as part of DWOC . Can you please assign this issue to me ?

@Ash515 today is the last day to make PR count. So if you add the label and assign this issue to me then I will make a PR asap.

**Comment by Ash515** [comment]
yeah you can
